export const GET_APPLICATIONS_REQUEST = 'GET_APPLICATIONS_REQUEST';
export const GET_APPLICATIONS_SUCCESS = 'GET_APPLICATIONS_SUCCESS';
export const GET_APPLICATIONS_FAILED = 'GET_APPLICATIONS_FAILED';
export const GET_APPLICATIONS_COMPLETE = 'GET_APPLICATIONS_COMPLETE';

export const ADD_APPLICATION_REQUEST = 'ADD_APPLICATION_REQUEST';
export const ADD_APPLICATION_SUCCESS = 'ADD_APPLICATION_SUCCESS';
export const ADD_APPLICATION_FAILED = 'ADD_APPLICATION_FAILED';
export const ADD_APPLICATION_COMPLETE = 'ADD_APPLICATION_COMPLETE';

export const DELETE_APPLICATION_REQUEST = 'DELETE_APPLICATION_REQUEST';
export const DELETE_APPLICATION_SUCCESS = 'DELETE_APPLICATION_SUCCESS';
export const DELETE_APPLICATION_FAILED = 'DELETE_APPLICATION_FAILED';
export const DELETE_APPLICATION_COMPLETE = 'DELETE_APPLICATION_COMPLETE';

export const UPDATE_APPLICATION_REQUEST = 'UPDATE_APPLICATION_REQUEST';
export const UPDATE_APPLICATION_SUCCESS = 'UPDATE_APPLICATION_SUCCESS';
export const UPDATE_APPLICATION_FAILED = 'UPDATE_APPLICATION_FAILED';
export const UPDATE_APPLICATION_COMPLETE = 'UPDATE_APPLICATION_COMPLETE';
