export const GET_APPLICANTS = 'GET_APPLICANTS'
export const GET_APPLICANTS_SUCCESS = 'GET_APPLICANTS_SUCCESS'

export const ADD_APPLICANTS = 'ADD_APPLICANTS'
export const ADD_APPLICANTS_SUCCESS = 'ADD_APPLICANTS_SUCCESS'

export const DELETE_APPLICANTS = 'DELETE_APPLICANTS'
export const DELETE_APPLICANTS_SUCCESS = 'DELETE_APPLICANTS_SUCCESS'

export const UPDATE_APPLICANTS = 'UPDATE_APPLICANTS'
export const UPDATE_APPLICANTS_SUCCESS = 'UPDATE_APPLICANTS_SUCCESS'
