export const GET_APPLICANTS_REQUEST = 'GET_APPLICANTS_REQUEST';
export const GET_APPLICANTS_SUCCESS = 'GET_APPLICANTS_SUCCESS';
export const GET_APPLICANTS_FAILED = 'GET_APPLICANTS_FAILED';
export const GET_APPLICANTS_COMPLETE = 'GET_APPLICANTS_COMPLETE';

export const ADD_APPLICANT_REQUEST = 'ADD_APPLICANT_REQUEST';
export const ADD_APPLICANT_SUCCESS = 'ADD_APPLICANT_SUCCESS';
export const ADD_APPLICANT_FAILED = 'ADD_APPLICANT_FAILED';
export const ADD_APPLICANT_COMPLETE = 'ADD_APPLICANT_COMPLETE';

export const DELETE_APPLICANT_REQUEST = 'DELETE_APPLICANT_REQUEST';
export const DELETE_APPLICANT_SUCCESS = 'DELETE_APPLICANT_SUCCESS';
export const DELETE_APPLICANT_FAILED = 'DELETE_APPLICANT_FAILED';
export const DELETE_APPLICANT_COMPLETE = 'DELETE_APPLICANT_COMPLETE';

export const UPDATE_APPLICANT_REQUEST = 'UPDATE_APPLICANT_REQUEST';
export const UPDATE_APPLICANT_SUCCESS = 'UPDATE_APPLICANT_SUCCESS';
export const UPDATE_APPLICANT_FAILED = 'UPDATE_APPLICANT_FAILED';
export const UPDATE_APPLICANT_COMPLETE = 'UPDATE_APPLICANT_COMPLETE';
