export const GET_DEPARTMENTS = 'GET_DEPARTMENTS'
export const GET_DEPARTMENTS_SUCCESS = 'GET_DEPARTMENTS_SUCCESS'

export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS'
export const ADD_DEPARTMENTS_SUCCESS = 'ADD_DEPARTMENTS_SUCCESS'

export const DELETE_DEPARTMENTS = 'DELETE_DEPARTMENTS'
export const DELETE_DEPARTMENTS_SUCCESS = 'DELETE_DEPARTMENTS_SUCCESS'

export const UPDATE_DEPARTMENTS = 'UPDATE_DEPARTMENTS'
export const UPDATE_DEPARTMENTS_SUCCESS = 'UPDATE_DEPARTMENTS_SUCCESS'
