export const SET_USERS_ACCESS_LEVEL = 'SET_USERS_ACCESS_LEVEL';
export const ADD_USER = 'ADD_USER';
export const GET_USERS = 'GET_USERS';
export const REMOVE_USER = 'REMOVE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const SHOW_ENABLED_FILTER = 'SHOW_ENABLED_FILTER';
