export const GET_SECOND_INTERVIEW_EVALUATIONS =
  'GET_SECOND_INTERVIEW_EVALUATIONS'
export const GET_SECOND_INTERVIEW_EVALUATIONS_SUCCESS =
  'GET_SECOND_INTERVIEW_EVALUATIONS_SUCCESS'

export const ADD_SECOND_INTERVIEW_EVALUATIONS =
  'ADD_SECOND_INTERVIEW_EVALUATIONS'
export const ADD_SECOND_INTERVIEW_EVALUATIONS_SUCCESS =
  'ADD_SECOND_INTERVIEW_EVALUATIONS_SUCCESS'

export const DELETE_SECOND_INTERVIEW_EVALUATIONS =
  'DELETE_SECOND_INTERVIEW_EVALUATIONS'
export const DELETE_SECOND_INTERVIEW_EVALUATIONS_SUCCESS =
  'DELETE_SECOND_INTERVIEW_EVALUATIONS_SUCCESS'

export const UPDATE_SECOND_INTERVIEW_EVALUATIONS =
  'UPDATE_SECOND_INTERVIEW_EVALUATIONS'
export const UPDATE_SECOND_INTERVIEW_EVALUATIONS_SUCCESS =
  'UPDATE_SECOND_INTERVIEW_EVALUATIONS_SUCCESS'
