export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAILED = 'GET_QUESTIONS_FAILED';
export const GET_QUESTIONS_COMPLETE = 'GET_QUESTIONS_COMPLETE';

export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_FAILED = 'ADD_QUESTION_FAILED';
export const ADD_QUESTION_COMPLETE = 'ADD_QUESTION_COMPLETE';

export const DELETE_QUESTION = 'DELETE_QUESTION';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_FAILED = 'DELETE_QUESTION_FAILED';
export const DELETE_QUESTION_COMPLETE = 'DELETE_QUESTION_COMPLETE';

export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
export const UPDATE_QUESTION_FAILED = 'UPDATE_QUESTION_FAILED';
export const UPDATE_QUESTION_COMPLETE = 'UPDATE_QUESTION_COMPLETE';
