export const GET_QUESTIONS = 'GET_QUESTIONS'
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS'

export const ADD_QUESTIONS = 'ADD_QUESTIONS'
export const ADD_QUESTIONS_SUCCESS = 'ADD_QUESTIONS_SUCCESS'

export const DELETE_QUESTIONS = 'DELETE_QUESTIONS'
export const DELETE_QUESTIONS_SUCCESS = 'DELETE_QUESTIONS_SUCCESS'

export const UPDATE_QUESTIONS = 'UPDATE_QUESTIONS'
export const UPDATE_QUESTIONS_SUCCESS = 'UPDATE_QUESTIONS_SUCCESS'
