export const GET_ACCOUNTS = 'GET_ACCOUNTS'
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS'

export const ADD_ACCOUNTS = 'ADD_ACCOUNTS'
export const ADD_ACCOUNTS_SUCCESS = 'ADD_ACCOUNTS_SUCCESS'

export const DELETE_ACCOUNTS = 'DELETE_ACCOUNTS'
export const DELETE_ACCOUNTS_SUCCESS = 'DELETE_ACCOUNTS_SUCCESS'

export const UPDATE_ACCOUNTS = 'UPDATE_ACCOUNTS'
export const UPDATE_ACCOUNTS_SUCCESS = 'UPDATE_ACCOUNTS_SUCCESS'
