export const GET_STEPS = 'GET_STEPS'
export const GET_STEPS_SUCCESS = 'GET_STEPS_SUCCESS'

export const ADD_STEPS = 'ADD_STEPS'
export const ADD_STEPS_SUCCESS = 'ADD_STEPS_SUCCESS'

export const DELETE_STEPS = 'DELETE_STEPS'
export const DELETE_STEPS_SUCCESS = 'DELETE_STEPS_SUCCESS'

export const UPDATE_STEPS = 'UPDATE_STEPS'
export const UPDATE_STEPS_SUCCESS = 'UPDATE_STEPS_SUCCESS'
