export const GET_FIRST_INTERVIEW_EVALUATIONS = 'GET_FIRST_INTERVIEW_EVALUATIONS'
export const GET_FIRST_INTERVIEW_EVALUATIONS_SUCCESS =
  'GET_FIRST_INTERVIEW_EVALUATIONS_SUCCESS'

export const ADD_FIRST_INTERVIEW_EVALUATIONS = 'ADD_FIRST_INTERVIEW_EVALUATIONS'
export const ADD_FIRST_INTERVIEW_EVALUATIONS_SUCCESS =
  'ADD_FIRST_INTERVIEW_EVALUATIONS_SUCCESS'

export const DELETE_FIRST_INTERVIEW_EVALUATIONS =
  'DELETE_FIRST_INTERVIEW_EVALUATIONS'
export const DELETE_FIRST_INTERVIEW_EVALUATIONS_SUCCESS =
  'DELETE_FIRST_INTERVIEW_EVALUATIONS_SUCCESS'

export const UPDATE_FIRST_INTERVIEW_EVALUATIONS =
  'UPDATE_FIRST_INTERVIEW_EVALUATIONS'
export const UPDATE_FIRST_INTERVIEW_EVALUATIONS_SUCCESS =
  'UPDATE_FIRST_INTERVIEW_EVALUATIONS_SUCCESS'
