export const GET_PHONE_EVALUATIONS = 'GET_PHONE_EVALUATIONS'
export const GET_PHONE_EVALUATIONS_SUCCESS = 'GET_PHONE_EVALUATIONS_SUCCESS'

export const ADD_PHONE_EVALUATIONS = 'ADD_PHONE_EVALUATIONS'
export const ADD_PHONE_EVALUATIONS_SUCCESS = 'ADD_PHONE_EVALUATIONS_SUCCESS'

export const DELETE_PHONE_EVALUATIONS = 'DELETE_PHONE_EVALUATIONS'
export const DELETE_PHONE_EVALUATIONS_SUCCESS =
  'DELETE_PHONE_EVALUATIONS_SUCCESS'

export const UPDATE_PHONE_EVALUATIONS = 'UPDATE_PHONE_EVALUATIONS'
export const UPDATE_PHONE_EVALUATIONS_SUCCESS =
  'UPDATE_PHONE_EVALUATIONS_SUCCESS'
