export const GET_APPLICATIONS = 'GET_APPLICATIONS'
export const GET_APPLICATIONS_SUCCESS = 'GET_APPLICATIONS_SUCCESS'

export const ADD_APPLICATIONS = 'ADD_APPLICATIONS'
export const ADD_APPLICATIONS_SUCCESS = 'ADD_APPLICATIONS_SUCCESS'

export const DELETE_APPLICATIONS = 'DELETE_APPLICATIONS'
export const DELETE_APPLICATIONS_SUCCESS = 'DELETE_APPLICATIONS_SUCCESS'

export const UPDATE_APPLICATIONS = 'UPDATE_APPLICATIONS'
export const UPDATE_APPLICATIONS_SUCCESS = 'UPDATE_APPLICATIONS_SUCCESS'
