export const CHANGE_GRADE = 'CHANGE_GRADE'
export const ADD_NOTES = 'ADD_NOTES'
export const REMOVE_NOTES = 'REMOVE_NOTES'
export const SUBMIT_GRADE = 'SUBMIT_GRADE'
export const SAVE_GRADE = 'SAVE_GRADE'