export const GET_POSITIONS = 'GET_POSITIONS'
export const GET_POSITIONS_SUCCESS = 'GET_POSITIONS_SUCCESS'

export const ADD_POSITIONS = 'ADD_POSITIONS'
export const ADD_POSITIONS_SUCCESS = 'ADD_POSITIONS_SUCCESS'

export const DELETE_POSITIONS = 'DELETE_POSITIONS'
export const DELETE_POSITIONS_SUCCESS = 'DELETE_POSITIONS_SUCCESS'

export const UPDATE_POSITIONS = 'UPDATE_POSITIONS'
export const UPDATE_POSITIONS_SUCCESS = 'UPDATE_POSITIONS_SUCCESS'
