export const ADD_POSITION = 'ADD_POSITION';
export const GET_POSITIONS = 'GET_POSITIONS';
export const REMOVE_POSITION = 'REMOVE_POSITION';
export const UPDATE_POSITION = 'UPDATE_POSITION';
export const SHOW_OPEN_FILTER = 'SHOW_OPEN_FILTER';
