export const ADD_POSITION = 'ADD_POSITION';
export const GET_POSITIONS = 'GET_POSITIONS';
export const DELETE_POSITION = 'DELETE_POSITION';
export const UPDATE_POSITION = 'UPDATE_POSITION';
export const ENABLE_POSITION = 'ENABLE_POSITION';
export const DISABLE_POSITION = 'DISABLE_POSITION';
export const SHOW_OPEN_FILTER = 'SHOW_OPEN_FILTER';
