export const GET_POSITIONS_REQUEST = 'GET_POSITIONS_REQUEST';
export const GET_POSITIONS_SUCCESS = 'GET_POSITIONS_SUCCESS';
export const GET_POSITIONS_FAILED = 'GET_POSITIONS_FAILED';
export const GET_POSITIONS_COMPLETE = 'GET_POSITIONS_COMPLETE';

export const ADD_POSITION_REQUEST = 'ADD_POSITION_REQUEST';
export const ADD_POSITION_SUCCESS = 'ADD_POSITION_SUCCESS';
export const ADD_POSITION_FAILED = 'ADD_POSITION_FAILED';
export const ADD_POSITION_COMPLETE = 'ADD_POSITION_COMPLETE';

export const DELETE_POSITION_REQUEST = 'DELETE_POSITION_REQUEST';
export const DELETE_POSITION_SUCCESS = 'DELETE_POSITION_SUCCESS';
export const DELETE_POSITION_FAILED = 'DELETE_POSITION_FAILED';
export const DELETE_POSITION_COMPLETE = 'DELETE_POSITION_COMPLETE';

export const UPDATE_POSITION_REQUEST = 'UPDATE_POSITION_REQUEST';
export const UPDATE_POSITION_SUCCESS = 'UPDATE_POSITION_SUCCESS';
export const UPDATE_POSITION_FAILED = 'UPDATE_POSITION_FAILED';
export const UPDATE_POSITION_COMPLETE = 'UPDATE_POSITION_COMPLETE';

