export const GET_JOB_POSTINGS = 'GET_JOB_POSTINGS'
export const GET_JOB_POSTINGS_SUCCESS = 'GET_JOB_POSTINGS_SUCCESS'

export const ADD_JOB_POSTINGS = 'ADD_JOB_POSTINGS'
export const ADD_JOB_POSTINGS_SUCCESS = 'ADD_JOB_POSTINGS_SUCCESS'

export const DELETE_JOB_POSTINGS = 'DELETE_JOB_POSTINGS'
export const DELETE_JOB_POSTINGS_SUCCESS = 'DELETE_JOB_POSTINGS_SUCCESS'

export const UPDATE_JOB_POSTINGS = 'UPDATE_JOB_POSTINGS'
export const UPDATE_JOB_POSTINGS_SUCCESS = 'UPDATE_JOB_POSTINGS_SUCCESS'

export const CHANGE_SELECTED_POSTING = 'CHANGE_SELECTED_POSTING'
