export const ADD_QUESTION = 'ADD_QUESTION';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const SHOW_ENABLED_FILTER = 'SHOW_ENABLED_FILTER';
export const QUESTION_STEP_FILTER = 'QUESTION_STEP_FILTER';