export const ADD_QUESTION = 'ADD_QUESTION';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const ENABLE_QUESTION = 'ENABLE_QUESTION';
export const DISABLE_QUESTION = 'DISABLE_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const SHOW_ENABLED_FILTER = 'SHOW_ENABLED_FILTER';
export const QUESTION_STEP_FILTER = 'QUESTION_STEP_FILTER';