export const GET_RESUME_EVALUATIONS = 'GET_RESUME_EVALUATIONS'
export const GET_RESUME_EVALUATIONS_SUCCESS = 'GET_RESUME_EVALUATIONS_SUCCESS'

export const ADD_RESUME_EVALUATIONS = 'ADD_RESUME_EVALUATIONS'
export const ADD_RESUME_EVALUATIONS_SUCCESS = 'ADD_RESUME_EVALUATIONS_SUCCESS'

export const DELETE_RESUME_EVALUATIONS = 'DELETE_RESUME_EVALUATIONS'
export const DELETE_RESUME_EVALUATIONS_SUCCESS =
  'DELETE_RESUME_EVALUATIONS_SUCCESS'

export const UPDATE_RESUME_EVALUATIONS = 'UPDATE_RESUME_EVALUATIONS'
export const UPDATE_RESUME_EVALUATIONS_SUCCESS =
  'UPDATE_RESUME_EVALUATIONS_SUCCESS'
