export const GET_ACCOUNT_LEVELS = 'GET_ACCOUNT_LEVELS'
export const GET_ACCOUNT_LEVELS_SUCCESS = 'GET_ACCOUNT_LEVELS_SUCCESS'

export const ADD_ACCOUNT_LEVELS = 'ADD_ACCOUNT_LEVELS'
export const ADD_ACCOUNT_LEVELS_SUCCESS = 'ADD_ACCOUNT_LEVELS_SUCCESS'

export const DELETE_ACCOUNT_LEVELS = 'DELETE_ACCOUNT_LEVELS'
export const DELETE_ACCOUNT_LEVELS_SUCCESS = 'DELETE_ACCOUNT_LEVELS_SUCCESS'

export const UPDATE_ACCOUNT_LEVELS = 'UPDATE_ACCOUNT_LEVELS'
export const UPDATE_ACCOUNT_LEVELS_SUCCESS = 'UPDATE_ACCOUNT_LEVELS_SUCCESS'
