export const GET_STEPS_REQUEST = 'GET_STEPS_REQUEST';
export const GET_STEPS_SUCCESS = 'GET_STEPS_SUCCESS';
export const GET_STEPS_FAILED = 'GET_STEPS_FAILED';
export const GET_STEPS_COMPLETE = 'GET_STEPS_COMPLETE';

export const ADD_STEP_REQUEST = 'ADD_STEP_REQUEST';
export const ADD_STEP_SUCCESS = 'ADD_STEP_SUCCESS';
export const ADD_STEP_FAILED = 'ADD_STEP_FAILED';
export const ADD_STEP_COMPLETE = 'ADD_STEP_COMPLETE';

export const DELETE_STEP_REQUEST = 'DELETE_STEP_REQUEST';
export const DELETE_STEP_SUCCESS = 'DELETE_STEP_SUCCESS';
export const DELETE_STEP_FAILED = 'DELETE_STEP_FAILED';
export const DELETE_STEP_COMPLETE = 'DELETE_STEP_COMPLETE';

export const UPDATE_STEP_REQUEST = 'UPDATE_STEP_REQUEST';
export const UPDATE_STEP_SUCCESS = 'UPDATE_STEP_SUCCESS';
export const UPDATE_STEP_FAILED = 'UPDATE_STEP_FAILED';
export const UPDATE_STEP_COMPLETE = 'UPDATE_STEP_COMPLETE';

export const SKIP_STEP = 'SKIP_STEP';

