export const ADD_STEP = 'ADD_STEP';
export const GET_STEPS = 'GET_STEPS';
export const REMOVE_STEP = 'REMOVE_STEP';
export const UPDATE_STEP = 'UPDATE_STEP';
export const SHOW_ENABLED_FILTER = 'SHOW_ENABLED_FILTER';
export const PROGRESSION_STEP_FILTER = 'PROGRESSION_STEP_FILTER';
export const SKIP_STEP = 'SKIP_STEP';